SELECT 
  FIRST_NAME,
  COUNT(*) AS NAME_COUNT
FROM (
  SELECT TRIM(SPLIT_PART(Cast, ' ', 1)) AS FIRST_NAME
  FROM Netflix_Titles
  WHERE LOWER(TYPE) IN ('movie', 'tv show')
)
GROUP BY FIRST_NAME
ORDER BY NAME_COUNT DESC
LIMIT 1;