CREATE OR REPLACE VIEW most_common_first_name_view AS
SELECT 
  FIRST_NAME,
  COUNT(*) AS NAME_COUNT
FROM (
  SELECT 
    TRIM(SPLIT_PART(CAST, ' ', 1)) AS FIRST_NAME
  FROM 
    Netflix_titles
  WHERE 
    TYPE IN ('Movie', 'TV Show')
    AND CAST IS NOT NULL
)
GROUP BY 
  FIRST_NAME
ORDER BY 
  NAME_COUNT DESC
LIMIT 1;